WITH
    EMP_DEP 
    AS 
    (
        SELECT 
            FIRST_NAME, 
            LAST_NAME, 
            JOB_ID, 
            DEPARTMENT_ID
        FROM 
            HR.EMPLOYEES
        WHERE 
            JOB_ID LIKE 'S%'
    ),
    JOB_TITLES 
    AS 
    (
        SELECT 
            JOB_ID, 
            JOB_TITLE, 
            MIN_SALARY, 
            MAX_SALARY
        FROM 
            HR.JOBS
    ),
    DEPARTMENT_NAME 
    AS
    (
        SELECT 
            DEPARTMENT_ID,
            DEPARTMENT_NAME
        FROM 
            HR.DEPARTMENTS
    )
SELECT 
    EMP_DEP.FIRST_NAME,
    EMP_DEP.LAST_NAME,
    EMP_DEP.JOB_ID,
    JOB_TITLES.JOB_TITLE,
    JOB_TITLES.MIN_SALARY,
    JOB_TITLES.MAX_SALARY,
    EMP_DEP.DEPARTMENT_ID,
    DEPARTMENT_NAME.DEPARTMENT_NAME
FROM
    EMP_DEP, 
    DEPARTMENT_NAME, 
    JOB_TITLES
WHERE 
    EMP_DEP.DEPARTMENT_ID = DEPARTMENT_NAME.DEPARTMENT_ID 
AND    
    EMP_DEP.JOB_ID = JOB_TITLES.JOB_ID
